In [4]:
import numpy as np

a = np.array([1,2,3,4])

b = np.array([4,5,6,7])


array([ 4, 10, 18, 28])

In [5]:
a * b

array([ 4, 10, 18, 28])

In [8]:
colors = np.random.random(100).reshape([10,10])*255
colors.astype(np.int8)

array([[-120,   -9,  118,  -63,   45,  -15,   75,  -43,   17,   38],
       [  98,   85,   27,    7,  106,  -21,   20,  -23,  -33, -112],
       [  78,  118,  -41,   12,   87,  -48,   62,   45,   -4,  110],
       [  48,    0,  -20,  112,  -85,  -88,  -84,   81,   57,   60],
       [-114,  121,  118,  -26,  107,   -7,  -90,  -92,   63,  -52],
       [ -16,   64,   22,   18,   57,   -4,  -26,   98,   33,  109],
       [ -39,   38, -104, -117,    6, -111, -117,   -3, -120,  127],
       [  -8,  -31, -100,    5,  -31,   87,  -37,  -17,  -15,  -36],
       [ -59,   58,   74,   71,   40,  104,   96,  -51,   93,  111],
       [ -55,  116, -108,  -11,   92,  -84,  -57,  -85, -104,  -57]],
      dtype=int8)

In [17]:
# gen RGB

from PIL import Image as im 
colors = np.random.random(3000000).reshape([1000,1000,3]).astype(np.float32)
data = im.fromarray(colors, 'RGB')

data.save("random.png")

data.show()

In [ ]:
# gen gray image


